DROP TABLE IF EXISTS Measurement;
DROP TABLE IF EXISTS Sensor;

CREATE TABLE IF NOT EXISTS Sensor(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL UNIQUE,
    CONSTRAINT PK_sensor_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Measurement(
    id int GENERATED BY DEFAULT AS IDENTITY,
    temperature double precision NOT NULL,
    is_raining boolean NOT NULL,
    created_date timestamp NOT NULL,
    sensor_id int,
    CONSTRAINT PK_measurement_id PRIMARY KEY (id),
    CONSTRAINT FK_sensor_measurement FOREIGN KEY (sensor_id)
        REFERENCES Sensor(id) ON DELETE CASCADE
);
